-- CarManager schema for Supabase (PostgreSQL)
-- Run this once in the Supabase Dashboard -> SQL Editor.

create table if not exists public.users (
  id bigint generated by default as identity primary key,
  name text not null,
  username text unique not null,
  password_hash text not null
);

create table if not exists public.cars (
  id bigint generated by default as identity primary key,
  name text not null,
  plate text,
  current_km integer not null default 0,
  last_service_km integer not null default 0,
  last_service_date date,
  service_interval_km integer not null default 10000
);

create table if not exists public.maintenance_logs (
  id bigint generated by default as identity primary key,
  car_id bigint not null references public.cars(id) on delete cascade,
  user_id bigint references public.users(id) on delete set null,
  date date not null,
  km integer not null,
  description text not null,
  cost double precision,
  is_service boolean not null default false,
  created_at timestamptz not null default now()
);

create table if not exists public.parking_locations (
  id bigint generated by default as identity primary key,
  car_id bigint not null references public.cars(id) on delete cascade,
  user_id bigint references public.users(id) on delete set null,
  lat double precision not null,
  lng double precision not null,
  accuracy double precision,
  created_at timestamptz not null default now()
);

-- The Express server talks to the database with the SECRET key (bypasses RLS).
-- Enabling RLS with no policies blocks the publishable/anon key entirely,
-- so nobody can read password hashes or data directly from the browser.
alter table public.users enable row level security;
alter table public.cars enable row level security;
alter table public.maintenance_logs enable row level security;
alter table public.parking_locations enable row level security;

-- Used by migrate.js after copying rows with their original SQLite ids,
-- so the auto-increment counters continue from the right place.
create or replace function public.sync_id_sequences()
returns void
language plpgsql
security definer
as $$
begin
  perform setval(pg_get_serial_sequence('public.users', 'id'),
                 coalesce((select max(id) from public.users), 0) + 1, false);
  perform setval(pg_get_serial_sequence('public.cars', 'id'),
                 coalesce((select max(id) from public.cars), 0) + 1, false);
  perform setval(pg_get_serial_sequence('public.maintenance_logs', 'id'),
                 coalesce((select max(id) from public.maintenance_logs), 0) + 1, false);
  perform setval(pg_get_serial_sequence('public.parking_locations', 'id'),
                 coalesce((select max(id) from public.parking_locations), 0) + 1, false);
end;
$$;
